language: go
dist: trusty

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcairo2-dev mercurial pkg-config wget -y
  - wget -O- "https://gist.githubusercontent.com/Civil/13df5aa7a6bc3bce1256c8c0f908587d/raw/a47c67bff43f7787afeda8d383a55da725d84980/travis-docker-build.sh" | /bin/bash -x
 

matrix:
  include:
    - go: 1.x
      env: BUILD_PACKAGES=true
    - go: 1.7.x
    - go: 1.8.x
    - go: master
