language: go
dist: trusty

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcairo2-dev mercurial pkg-config -y
  - docker pull civilus/gographite-build-centos:6 &
    docker pull civilus/gographite-build-centos:7 &
    docker pull civilus/gographite-build-ubuntu:14.04 &
    docker pull civilus/gographite-build-ubuntu:16.04 &
  - wait
  - gem install package_cloud
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "${FORCE_BUILD}" == "true" ]; then
        mkdir -p pkg;
        for i in centos:6 centos:7 ubuntu:14.04 ubuntu:16.04; do
            docker start civilus/gographite-build-${i}
            docker cp /home/travis/gopath civilus/gographite-build-${i}:/root/go;
            docker run civilus/gographite-build-${i} /bin/bash '/root/pack.sh' || exit 1;
            docker cp civilus/gographite-build-${i}:~/pkg/* ./pkg/;
            docker stop civilus/gographite-build-${i}
        done;
        pushd pkg;
        for d in $(ls); do
            pushd ${d};
            for v in $(ls); do
                pushd ${v};
                for r in $(ls); do
                    package_cloud push go-graphite/${r}/${d}/${v} ./${r}/*;
                done;
                popd;
            done;
            popd;
        done;
        popd;
    fi

go:
  - 1.x
  - 1.7.x
  - 1.8.x
  - master
